sprite_index = sprRushTeleport;
teleportTimer = 0;
yspeed = 0;
player_x = 0;
player_y = 0;
image_speed = 0;
image_index = 0;
spd = 1;
anim_spd = 10 / room_speed;
prev_img_index = image_index;
delivering = false;
leaving = false;
delivered = false;
items = 1;
itemsCalled = 5;
itemsLeft = items;
ground = false;
called = false;

